#!/bin/bash
# E190 — Lesson Consolidation Detector
#
# Read-only script that detects similar Tier 0 memory lessons using
# Jaccard similarity on frontmatter tags and cosine similarity on body text.
# Reports pairs (or transitive clusters) whose combined score >= threshold.
#
# Output: JSON array to stdout, human-readable markdown table to REPORT_PATH
# (if set). Never writes to the Tier 0 memory directory.
#
# Algorithm:
#   - Jaccard on tags:   |A.tags ∩ B.tags| / |A.tags ∪ B.tags|
#   - Cosine on body:    TF word-frequency vectors (tokens >= 4 chars, lowercased)
#                        normalized dot product
#   - Combined score:    0.5 * jaccard + 0.5 * cosine
#   - Cluster:           transitive closure of pairs with combined >= THRESHOLD
#
# Env overrides (test injection):
#   TEMPLATE_MEMORY_DIR      override ~/.claude/template-memory (test isolation)
#   CONSOLIDATION_THRESHOLD  similarity threshold (default 0.7)
#   REPORT_PATH              if set, write markdown report here
#   AUDIT_LOG_PATH           override .claude/audit.jsonl
#   CLOCK_DATE               override date for audit event (YYYY-MM-DD)
#   CLOCK_TS                 override timestamp for audit event (ISO 8601)

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TIER0_DIR="${TEMPLATE_MEMORY_DIR:-$HOME/.claude/template-memory}"
THRESHOLD="${CONSOLIDATION_THRESHOLD:-0.7}"
AUDIT_LOG="${AUDIT_LOG_PATH:-$REPO_ROOT/.claude/audit.jsonl}"
SIDECAR_JSON="${LESSON_TAGS_JSON:-$REPO_ROOT/scripts/memory/lesson-tags.json}"

# ---- helpers ----------------------------------------------------------------

ts_now() {
  if [ -n "${CLOCK_TS:-}" ]; then echo "$CLOCK_TS"; return; fi
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

date_now() {
  if [ -n "${CLOCK_DATE:-}" ]; then echo "$CLOCK_DATE"; return; fi
  date -u +"%Y-%m-%d"
}

# ---- emit audit event -------------------------------------------------------

emit_audit() {
  local clusters="$1" lessons_involved="$2"
  command -v jq >/dev/null 2>&1 || return 0
  mkdir -p "$(dirname "$AUDIT_LOG")" 2>/dev/null || true
  local ts; ts=$(ts_now)
  local epic
  epic=$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null \
    | sed -n 's/.*\(E[0-9]\{1,\}\).*/\1/Ip' \
    | tr '[:lower:]' '[:upper:]')
  [ -z "$epic" ] && epic="none"
  jq -n -c \
    --arg ts "$ts" \
    --arg epic "$epic" \
    --argjson clusters "$clusters" \
    --argjson lessons_involved "$lessons_involved" \
    '{ts:$ts,event:"consolidation_detected",clusters:$clusters,lessons_involved:$lessons_involved,epic:$epic}' \
    >> "$AUDIT_LOG" 2>/dev/null || true
}

# ---- write markdown report --------------------------------------------------

write_report() {
  local json_output="$1"
  local path="$2"
  local date_str; date_str=$(date_now)

  {
    echo "# Consolidation Candidates — $date_str"
    echo
    echo "> Generated by \`scripts/memory/consolidation-detect.sh\` (E190)."
    echo "> Review pairs below and decide: merge, dismiss, split, or archive-one."
    echo "> **Human gate — no auto-merge.**"
    echo

    python3 - "$json_output" <<'PYEOF'
import sys, json

data = json.loads(sys.argv[1])
if not data:
    print("_No consolidation candidates detected (all Tier 0 lessons are sufficiently distinct)._")
    sys.exit(0)

# Summary table
print("| Cluster | Lesson A | Lesson B | Avg Overlap |")
print("|---------|----------|----------|-------------|")
for c in data:
    cid = c["cluster_id"]
    members = [l["name"] for l in c["lessons"]]
    avg = c["avg_overlap"]
    for i in range(len(members)):
        for j in range(i+1, len(members)):
            print(f"| {cid} | {members[i]} | {members[j]} | {avg:.4f} |")

print()
print("## Per-Cluster Details")
print()
for c in data:
    cid = c["cluster_id"]
    avg = c["avg_overlap"]
    detected = c["detected_at"]
    print(f"### {cid} — avg_overlap={avg}")
    print()
    for l in c["lessons"]:
        print(f"- `{l['name']}` (score={l['score']:.4f})")
    print()
    print(f"Detected: {detected}")
    print()
    print("**Action (human):** merge / dismiss / split / archive-one")
    print()
PYEOF
  } > "$path"
}

# ---- Python3 similarity + clustering engine ---------------------------------
# Accepts file paths as command-line arguments.
# Reads lesson data, computes pairwise Jaccard+cosine, clusters transitively.
# Outputs JSON clusters to stdout.

run_similarity_engine() {
  local threshold="$1" sidecar_json="$2"; shift 2
  python3 - "$threshold" "$sidecar_json" "$@" <<'PYEOF'
import sys, json, math, re, os

threshold = float(sys.argv[1])
sidecar_path = sys.argv[2]
paths = sys.argv[3:]

# Load sidecar tag map (lesson-tags.json "defaults" section).
# Used as fallback when a lesson has no tags in its frontmatter.
_sidecar_tags = {}
try:
    if os.path.isfile(sidecar_path):
        with open(sidecar_path, "r", encoding="utf-8") as _fh:
            _sidecar_data = json.load(_fh)
        for _name, _entry in _sidecar_data.get("defaults", {}).items():
            _sidecar_tags[_name] = [t.lower() for t in _entry.get("tags", [])]
except Exception:
    pass

STOPWORDS = {
    "the","and","for","are","but","not","you","all","any","can","her",
    "was","one","our","out","who","get","has","him","his","how","its",
    "may","new","now","old","see","two","way","who","boy","did","got",
    "let","man","put","say","she","too","use","had","this","that","with",
    "have","from","they","been","just","like","will","your","into","more",
    "also","some","then","than","when","each","even","most","what","such",
    "well","both","true","false","none","null","very","than","upon",
}

def parse_lesson(path):
    name = os.path.basename(path)
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            content = fh.read()
    except Exception:
        return {"name": name, "tags": set(), "vec": {}}

    tags = []
    in_fm = False
    fm_count = 0
    capturing_tags = False
    body_lines = []
    past_fm = False

    for line in content.splitlines():
        stripped = line.strip()
        if stripped == "---":
            fm_count += 1
            if fm_count == 1:
                in_fm = True
                continue
            elif fm_count == 2:
                in_fm = False
                past_fm = True
                continue
        if in_fm:
            if capturing_tags:
                if stripped.startswith("- "):
                    tag = stripped[2:].strip().strip("'\"").lower()
                    if tag:
                        tags.append(tag)
                    continue
                else:
                    # Only stop capturing if next key starts (non-indented)
                    if not (line.startswith(" ") or line.startswith("\t")):
                        capturing_tags = False
            if stripped.startswith("tags:"):
                rest = stripped[5:].strip()
                if rest.startswith("[") and rest.endswith("]"):
                    inner = rest[1:-1]
                    for t in inner.split(","):
                        t = t.strip().strip("'\"").lower()
                        if t:
                            tags.append(t)
                elif rest == "":
                    capturing_tags = True
                elif rest:
                    tags.append(rest.strip("'\"").lower())
        elif past_fm or fm_count == 0:
            body_lines.append(line)
            past_fm = True

    body = "\n".join(body_lines)
    tokens = [t for t in re.findall(r"[a-z]{4,}", body.lower()) if t not in STOPWORDS]
    freq = {}
    for t in tokens:
        freq[t] = freq.get(t, 0) + 1
    total = len(tokens) or 1
    vec = {k: v/total for k, v in freq.items()}

    # E197: if no tags found in frontmatter, fall back to sidecar lesson-tags.json.
    # Frontmatter always wins; sidecar fills the gap for lessons not yet
    # re-promoted with E182 frontmatter (12 of 14 lessons store tags only in sidecar).
    if not tags and name in _sidecar_tags:
        tags = list(_sidecar_tags[name])

    return {"name": name, "tags": set(tags), "vec": vec}

def cosine(va, vb):
    keys = set(va) & set(vb)
    if not keys:
        return 0.0
    dot = sum(va[k]*vb[k] for k in keys)
    na = math.sqrt(sum(x*x for x in va.values()))
    nb = math.sqrt(sum(x*x for x in vb.values()))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)

def jaccard(sa, sb):
    union = sa | sb
    if not union:
        return 0.0
    return len(sa & sb) / len(union)

lessons = [parse_lesson(p) for p in paths]
n = len(lessons)

pairs = []
for i in range(n):
    for j in range(i+1, n):
        a, b = lessons[i], lessons[j]
        jac = jaccard(a["tags"], b["tags"])
        cos = cosine(a["vec"], b["vec"])
        combined = 0.5 * jac + 0.5 * cos
        if combined >= threshold:
            pairs.append({
                "lesson_a": a["name"],
                "lesson_b": b["name"],
                "jaccard": round(jac, 4),
                "cosine": round(cos, 4),
                "combined": round(combined, 4),
            })

# Union-find for transitive closure
parent = {}
def find(x):
    parent.setdefault(x, x)
    if parent[x] != x:
        parent[x] = find(parent[x])
    return parent[x]
def union(x, y):
    px, py = find(x), find(y)
    if px != py:
        parent[px] = py

for p in pairs:
    union(p["lesson_a"], p["lesson_b"])

cluster_map = {}
for p in pairs:
    root = find(p["lesson_a"])
    cluster_map.setdefault(root, set())
    cluster_map[root].add(p["lesson_a"])
    cluster_map[root].add(p["lesson_b"])

import datetime
try:
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
except AttributeError:
    now = datetime.datetime.utcnow().isoformat() + "Z"

clusters = []
for cid, (root, members) in enumerate(cluster_map.items(), 1):
    members = sorted(members)
    relevant_pairs = [p for p in pairs
                      if p["lesson_a"] in members and p["lesson_b"] in members]
    avg_overlap = round(
        sum(p["combined"] for p in relevant_pairs) / max(len(relevant_pairs), 1),
        4
    )
    member_scores = {}
    for m in members:
        max_score = max(
            (p["combined"] for p in pairs
             if p["lesson_a"] == m or p["lesson_b"] == m),
            default=0.0
        )
        member_scores[m] = max_score

    clusters.append({
        "cluster_id": f"c{cid}",
        "lessons": [{"name": m, "score": member_scores[m]} for m in members],
        "avg_overlap": avg_overlap,
        "detected_at": now,
    })

print(json.dumps(clusters, indent=2))
PYEOF
}

# ---- main -------------------------------------------------------------------

main() {
  # Handle missing Tier 0 dir gracefully
  if [ ! -d "$TIER0_DIR" ]; then
    echo "[]"
    emit_audit 0 0
    return 0
  fi

  # Collect all .md lesson files (exclude meta + archive files)
  local files=()
  while IFS= read -r f; do
    local base; base=$(basename "$f")
    case "$base" in
      README.md|CLAUDE.md|NEW_PROJECT_PRIMER.md) continue ;;
      *archive*|*Archive*) continue ;;
    esac
    files+=("$f")
  done < <(find "$TIER0_DIR" -maxdepth 1 -name "*.md" -not -path "*/_archive/*" 2>/dev/null | sort)

  local file_count="${#files[@]}"

  # With 0 or 1 lesson, no pairs possible
  if [ "$file_count" -lt 2 ]; then
    echo "[]"
    emit_audit 0 0
    return 0
  fi

  # Run similarity engine (passes file paths directly — no stdin/pipe conflict).
  # E197: sidecar_json passed as second arg for tag fallback resolution.
  local json_output
  json_output=$(run_similarity_engine "$THRESHOLD" "$SIDECAR_JSON" "${files[@]}")

  # Count clusters and lessons involved for audit
  local cluster_count lessons_involved
  cluster_count=$(echo "$json_output" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(len(d))" 2>/dev/null || echo "0")
  lessons_involved=$(echo "$json_output" | python3 -c "
import sys,json
d=json.load(sys.stdin)
names=set()
for c in d:
    for l in c['lessons']:
        names.add(l['name'])
print(len(names))
" 2>/dev/null || echo "0")

  # Emit audit event
  emit_audit "$cluster_count" "$lessons_involved"

  # Write markdown report if REPORT_PATH is set
  if [ -n "${REPORT_PATH:-}" ]; then
    write_report "$json_output" "$REPORT_PATH"
  fi

  # Output JSON to stdout
  echo "$json_output"
}

main "$@"
