/**
 * E21 — Build manifest writer
 * Writes .build-manifest.yaml with project config and step results.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import YAML from "yaml";
import type { BuildManifest, ProjectConfig, StepResult, PrereqResult } from "./types.js";

/**
 * Build the manifest object from collected data.
 */
export function buildManifest(
  config: ProjectConfig,
  prereqs: PrereqResult[],
  steps: StepResult[],
): BuildManifest {
  const prerequisites: Record<string, string> = {};
  for (const p of prereqs) {
    if (p.found) {
      prerequisites[p.name] = p.found;
    }
  }

  return {
    version: "1.0",
    created_at: new Date().toISOString(),
    project: {
      name: config.slug,
      display_name: config.displayName,
      description: config.description,
      author: config.author,
    },
    config: {
      database: config.dbName,
      theme: config.theme,
      oauth_providers: [...config.oauthProviders],
      deploy_target: config.deployTarget,
    },
    prerequisites,
    steps_completed: steps,
  };
}

/**
 * Write the build manifest to disk as YAML.
 */
export function writeManifest(
  projectRoot: string,
  manifest: BuildManifest,
): string {
  const filePath = join(projectRoot, ".build-manifest.yaml");
  const header = "# .build-manifest.yaml — auto-generated by new-site CLI\n";
  const yamlContent = YAML.stringify(manifest, { indent: 2 });
  writeFileSync(filePath, header + yamlContent, "utf-8");
  return filePath;
}

/**
 * Serialize manifest to YAML string (for testing).
 */
export function manifestToYaml(manifest: BuildManifest): string {
  return YAML.stringify(manifest, { indent: 2 });
}
