/**
 * E21 — File scaffolding
 * Template variable replacement and domain feature removal.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import type { ProjectConfig } from "./types.js";

/** Template placeholder map derived from project config. */
export function buildReplacements(config: ProjectConfig): Record<string, string> {
  const dbUser = config.dbName + "_user";
  const dbPass = config.dbName + "_pass";
  return {
    "{{PROJECT_SLUG}}": config.slug,
    "{{PROJECT_DISPLAY}}": config.displayName,
    "{{PROJECT_DESCRIPTION}}": config.description,
    "{{DB_NAME}}": config.dbName,
    "{{AUTHOR}}": config.author,
    "{{DEFAULT_THEME}}": config.theme,
    // Generic config defaults → project-specific values
    "saas_dev": config.dbName,
    "saas_user": dbUser,
    "saas_pass": dbPass,
    "ai-coding-template-pipeline": `${config.slug}-pipeline`,
  };
}

/** Apply template variable replacement to a string. */
export function applyReplacements(
  content: string,
  replacements: Record<string, string>,
): string {
  let result = content;
  for (const [placeholder, value] of Object.entries(replacements)) {
    result = result.replaceAll(placeholder, value);
  }
  return result;
}

/**
 * Files to process with template variable replacement.
 * Paths are relative to project root.
 */
const TEMPLATE_FILES = [
  "package.json",
  "pyproject.toml",
  "Makefile",
  "docker-compose.yml",
  "CLAUDE.md",
  "TECHSTACK.md",
  "server/app/core/config.py",
  "server/alembic.ini",
  "server/.env.example",
  ".claude-plugin/plugin.json",
  ".env.local",
  ".env.production",
];


/**
 * Generate a .env file from project config.
 *
 * E75-S2: Aligned with server/.env.example — includes EMAIL_PROVIDER,
 * EMAIL_FROM, LOG_FORMAT, and all current env vars.
 */
export function generateEnvContent(config: ProjectConfig): string {
  const dbUser = config.dbName + "_user";
  const dbPass = config.dbName + "_pass";

  const lines = [
    "# Auto-generated by new-site CLI",
    `# Project: ${config.displayName}`,
    "",
    "# ─── Database ─────────────────────────────────────────────────",
    `DATABASE_URL=postgresql+asyncpg://${dbUser}:${dbPass}@localhost:5432/${config.dbName}`,
    "",
    "# ─── JWT Secrets ──────────────────────────────────────────────",
    `SECRET_KEY=${randomBytes(32).toString("hex")}`,
    `REFRESH_SECRET_KEY=${randomBytes(32).toString("hex")}`,
    "ACCESS_TOKEN_EXPIRE_MINUTES=15",
    "REFRESH_TOKEN_EXPIRE_DAYS=30",
    "",
  ];

  if (config.oauthProviders.includes("google")) {
    lines.push(
      "# ─── Google OAuth2 ────────────────────────────────────────────",
      "GOOGLE_CLIENT_ID=",
      "GOOGLE_CLIENT_SECRET=",
      "",
    );
  }

  if (config.oauthProviders.includes("github")) {
    lines.push(
      "# ─── GitHub OAuth2 ────────────────────────────────────────────",
      "GITHUB_CLIENT_ID=",
      "GITHUB_CLIENT_SECRET=",
      "",
    );
  }

  lines.push(
    "# ─── Email ────────────────────────────────────────────────────",
    "EMAIL_PROVIDER=console",
    "EMAIL_FROM=noreply@localhost",
    "",
    "# ─── Logging ─────────────────────────────────────────────────",
    "LOG_FORMAT=console",
    "",
    "# ─── App ─────────────────────────────────────────────────────",
    "DEBUG=true",
    "ENVIRONMENT=development",
    "ALLOWED_ORIGINS_STR=http://localhost:3000,http://localhost:5173",
    "RATE_LIMIT_AUTH=15/minute",
    "RATE_LIMIT_GENERAL=200/minute",
    "",
    "# ─── Session Cleanup ────────────────────────────────────────",
    "SESSION_CLEANUP_INTERVAL_MINUTES=60",
    "SESSION_RETENTION_DAYS=7",
    "",
    "# ─── Client (set at build time) ─────────────────────────────",
    "VITE_API_URL=http://localhost:8080",
    "",
  );

  return lines.join("\n");
}

/**
 * Generate a .env.example (secrets redacted).
 */
export function generateEnvExampleContent(config: ProjectConfig): string {
  return generateEnvContent(config)
    .replace(/SECRET_KEY=.*/g, "SECRET_KEY=<generate-a-random-string>")
    .replace(/REFRESH_SECRET_KEY=.*/g, "REFRESH_SECRET_KEY=<generate-a-random-string>");
}

/**
 * Run template variable replacement on known files.
 */
export function scaffoldFiles(
  projectRoot: string,
  config: ProjectConfig,
): { processed: string[]; skipped: string[] } {
  const replacements = buildReplacements(config);
  const processed: string[] = [];
  const skipped: string[] = [];

  for (const relPath of TEMPLATE_FILES) {
    const fullPath = join(projectRoot, relPath);
    if (!existsSync(fullPath)) {
      skipped.push(relPath);
      continue;
    }
    const content = readFileSync(fullPath, "utf-8");
    const updated = applyReplacements(content, replacements);
    if (updated !== content) {
      writeFileSync(fullPath, updated, "utf-8");
      processed.push(relPath);
    } else {
      skipped.push(relPath);
    }
  }

  // Write .env and .env.example (root + server)
  const envContent = generateEnvContent(config);
  writeFileSync(join(projectRoot, ".env"), envContent, "utf-8");
  processed.push(".env");
  const serverDir = join(projectRoot, "server");
  if (existsSync(serverDir)) {
    writeFileSync(join(serverDir, ".env"), envContent, "utf-8");
    processed.push("server/.env");
  }
  writeFileSync(
    join(projectRoot, ".env.example"),
    generateEnvExampleContent(config),
    "utf-8",
  );
  processed.push(".env.example");

  return { processed, skipped };
}

