/**
 * GET /api/openapi — E281.
 *
 * Public (no auth) — it's the API contract document. Returns the OpenAPI 3.1 doc
 * as application/json, built IN MEMORY from the Zod-derived registry (it does NOT
 * read docs/openapi.yaml at runtime, so it works in the standalone build).
 *
 * The YAML mirror (docs/openapi.yaml) is generated by `pnpm openapi:generate` from
 * the same buildOpenApiDocument() source.
 */

import { buildOpenApiDocument } from "@/lib/openapi/registry"

export async function GET() {
  return Response.json(buildOpenApiDocument())
}
