"""Alembic autogenerate hooks for UUID normalization (E63).

Extracted from env.py so they can be imported and tested independently.
"""

import sqlalchemy as sa

from app.models.base import GUID

try:
    from sqlalchemy.dialects.postgresql import UUID as PG_UUID
except ImportError:
    PG_UUID = None  # type: ignore[assignment,misc]

# All UUID-like SQLAlchemy types that should render as sa.Uuid()
_UUID_TYPE_NAMES = {"UUID", "Uuid", "GUID"}


def _is_uuid_like(obj: object) -> bool:
    """Return True if obj is any UUID-like column type."""
    # GUID TypeDecorator
    if isinstance(obj, GUID):
        return True
    # sa.Uuid() — the standard SQLAlchemy 2.0 type
    if isinstance(obj, sa.Uuid):
        return True
    # PostgreSQL native UUID
    if PG_UUID is not None and isinstance(obj, PG_UUID):
        return True
    # sa.CHAR(32) or CHAR(36) — SQLite UUID storage (sa.Uuid() reflects as 32, GUID as 36)
    if isinstance(obj, sa.CHAR) and getattr(obj, "length", None) in (32, 36):
        return True
    # Fallback: check class name for any other UUID variants
    cls_name = type(obj).__name__
    if cls_name in _UUID_TYPE_NAMES:
        return True
    return False


def render_item(type_: str, obj: object, autogen_context: object) -> str | bool:
    """Normalize all UUID-like types to sa.Uuid() in autogenerated migrations.

    Returns the string representation for type renders, or False to use
    Alembic's default rendering for non-UUID types.
    """
    if type_ == "type" and _is_uuid_like(obj):
        return "sa.Uuid()"
    # Return False to let Alembic handle all other types normally
    return False


def compare_type(
    context: object,
    inspected_column: sa.Column,  # type: ignore[type-arg]
    metadata_column: sa.Column,  # type: ignore[type-arg]
    inspected_type: sa.types.TypeEngine,
    metadata_type: sa.types.TypeEngine,
) -> bool | None:
    """Treat GUID <-> native UUID as equivalent to prevent spurious ALTERs.

    Returns:
        False — types are equivalent, skip ALTER
        True  — types differ, emit ALTER
        None  — let Alembic decide (default comparison)
    """
    # If both sides are UUID-like, they're equivalent
    if _is_uuid_like(inspected_type) and _is_uuid_like(metadata_type):
        return False

    # If one side is UUID-like and the other isn't, they genuinely differ
    if _is_uuid_like(inspected_type) != _is_uuid_like(metadata_type):
        return True

    # Let Alembic handle all other comparisons
    return None
