#!/usr/bin/env node
/*
 * service-map.cjs — draw how a service fits together FROM THE REAL IMPORT GRAPH, not a whiteboard.
 *
 * Parses the actual `import`/`export … from`/`import()` edges across the Next.js app, resolves the
 * `@/` alias + relative paths, and emits a Mermaid graph + an edge table for the slice of the graph
 * that matches a seed (a module-name substring, e.g. "billing", "items", "notifications").
 *
 * Usage:
 *   node scripts/service-map.cjs <seed...> [--out FILE] [--depth N]
 *   node scripts/service-map.cjs billing                 # billing slice → prints to stdout
 *   node scripts/service-map.cjs items api-keys --out /tmp/domains.md
 *
 * "Drawn from the code": every node + edge below is a real import statement. A module with 0
 * importers is flagged as an orphan (dead/phantom) — exactly the rot a whiteboard hides.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const APP = path.join(ROOT, "next-app");
const SRC_DIRS = ["lib", "actions", "app", "components"].map((d) => path.join(APP, d));
const args = process.argv.slice(2);
const outIdx = args.indexOf("--out");
const OUT = outIdx >= 0 ? args[outIdx + 1] : null;
const seeds = args.filter((a) => !a.startsWith("--") && (outIdx < 0 || a !== args[outIdx + 1])).map((s) => s.toLowerCase());
if (!seeds.length) { console.error("usage: service-map.cjs <seed...> [--out FILE]"); process.exit(2); }

// ── 1. collect source files (skip tests + generated) ────────────────────────
function walk(dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { if (!/node_modules|\.next|coverage/.test(p)) walk(p, acc); }
    else if (/\.(ts|tsx)$/.test(e.name) && !/\.test\.ts/.test(e.name)) acc.push(p);
  }
  return acc;
}
const files = SRC_DIRS.flatMap((d) => walk(d));
const rel = (p) => path.relative(APP, p).replace(/\\/g, "/");
const exists = (p) => { for (const x of [p, p + ".ts", p + ".tsx", path.join(p, "index.ts"), path.join(p, "index.tsx")]) if (fs.existsSync(x) && fs.statSync(x).isFile?.()) return rel(fs.existsSync(x + ".ts") ? x + ".ts" : x); return null; };

// resolve an import specifier from a file → internal rel-path | {external} | null
function resolve(spec, fromFile) {
  if (spec.startsWith("@/")) return exists(path.join(APP, spec.slice(2)));
  if (spec.startsWith(".")) return exists(path.resolve(path.dirname(fromFile), spec));
  return null; // bare package → external
}

// ── 2. build the graph: out-edges (imports) + external deps per module ───────
const IMP = /(?:from\s+|import\s*\(\s*)["']([^"']+)["']/g;
const graph = new Map(); // relPath -> { imports:Set, externals:Set }
for (const f of files) {
  const r = rel(f), txt = fs.readFileSync(f, "utf8");
  const node = graph.get(r) || { imports: new Set(), externals: new Set() };
  let m; while ((m = IMP.exec(txt))) {
    const spec = m[1];
    if (spec.startsWith("@/") || spec.startsWith(".")) { const t = resolve(spec, f); if (t) node.imports.add(t); }
    else if (!spec.startsWith("next/") && spec !== "react" && spec !== "react-dom") node.externals.add(spec.split("/")[0]);
  }
  graph.set(r, node);
}
// reverse edges (importers)
const importers = new Map();
for (const [r, n] of graph) for (const dep of n.imports) (importers.get(dep) || importers.set(dep, new Set()).get(dep)).add(r);

// ── 3. select the slice matching the seed(s) ────────────────────────────────
const isSeed = (r) => seeds.some((s) => r.toLowerCase().includes(s));
const seedNodes = [...graph.keys()].filter(isSeed);
const slice = new Set(seedNodes);
// add transitive imports (the service's dependencies) + direct importers (its consumers)
for (const s of seedNodes) {
  const stack = [...(graph.get(s)?.imports || [])];
  while (stack.length) { const d = stack.pop(); if (!slice.has(d)) { slice.add(d); stack.push(...(graph.get(d)?.imports || [])); } }
  for (const c of importers.get(s) || []) slice.add(c);
}

// ── 4. classify + emit ──────────────────────────────────────────────────────
const id = (r) => "n" + [...slice].indexOf(r);
const short = (r) => r.replace(/^lib\//, "").replace(/\.(ts|tsx)$/, "");
const kind = (r) => r.startsWith("actions/") ? "action" : r.startsWith("app/") ? "page" : r.startsWith("components/") ? "component" : "lib";
// Next.js pages/route-handlers + Server Actions are ENTRY POINTS — nothing imports them (the
// router/form invokes them), so 0 importers is expected, not dead. Only a lib/component with 0
// importers is a true orphan.
const isEntry = (r) => kind(r) === "page" || kind(r) === "action";
const lines = [];
const P = (s = "") => lines.push(s);

P(`# Service map: \`${seeds.join(" / ")}\` — from the real import graph`);
P(`\n> Generated by \`scripts/service-map.cjs ${seeds.join(" ")}\` — every node + edge is a real \`import\`.`);

if (!seedNodes.length) {
  P(`\n## ⚠ No modules match \`${seeds.join("/")}\` in the import graph.`);
  P(`\nScanned ${files.length} source files under \`next-app/{lib,actions,app,components}\`; **0** import any module whose path contains \`${seeds.join("\`/\`")}\`. If a whiteboard/registry/doc says this service exists, it is a **phantom** — there is no code wired in. (Re-run after adding the code; if edges appear, it's real.)`);
} else {
  const orphans = seedNodes.filter((s) => !(importers.get(s)?.size) && !isEntry(s));
  const ext = new Set(); for (const r of slice) for (const e of graph.get(r)?.externals || []) ext.add(e);
  P(`\n**${slice.size}** modules in the slice · **${seedNodes.length}** seed match(es) · external deps: ${ext.size ? [...ext].map((e) => "`" + e + "`").join(", ") : "**none** (pure logic + framework only)"}.`);
  if (orphans.length) P(`\n⚠ **Orphan(s) (0 importers — dead/unwired):** ${orphans.map((o) => "`" + short(o) + "`").join(", ")}`);

  P(`\n## Mermaid (import edges)`);
  P("```mermaid");
  P("graph LR");
  for (const r of slice) {
    const k = kind(r), label = short(r) + (isSeed(r) ? "" : "");
    const shape = k === "action" ? `["${label}<br/>(action)"]` : k === "page" ? `("${label}")` : k === "component" ? `>"${label}"]` : `["${label}"]`;
    P(`  ${id(r)}${shape}${isSeed(r) ? ":::seed" : ""}`);
  }
  for (const r of slice) for (const dep of graph.get(r)?.imports || []) if (slice.has(dep)) P(`  ${id(r)} --> ${id(dep)}`);
  P("  classDef seed fill:#dff,stroke:#06c,stroke-width:2px;");
  P("```");

  P(`\n## Edge table (verbatim from the code)`);
  P(`| module | kind | imports (internal) | imported by |`);
  P(`|---|---|---|---|`);
  for (const r of [...slice].sort()) {
    const n = graph.get(r) || { imports: new Set() };
    const imps = [...n.imports].filter((d) => slice.has(d)).map(short).join(" · ") || "—";
    const cons = [...(importers.get(r) || [])].map(short).join(" · ") || (isEntry(r) ? "**(entry point)**" : "**(none — orphan ⚠)**");
    P(`| \`${short(r)}\` | ${kind(r)} | ${imps} | ${cons} |`);
  }
}
P(`\n---\n*Method: regex over \`import … from\` / \`import()\` in next-app/{lib,actions,app,components} (.ts/.tsx, tests excluded), \`@/\`→next-app + relative resolution. Re-run to refresh.*`);

const out = lines.join("\n") + "\n";
if (OUT) { fs.writeFileSync(OUT, out); console.error(`wrote ${OUT}`); } else process.stdout.write(out);
